databases:
  - name: sodoto-db
    plan: free

services:
  - type: web
    name: sodoto-api
    runtime: ruby
    plan: free
    buildCommand: "./bin/build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sodoto-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2

