# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # min_messages: notice

test:
  <<: *default
  database: test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
